<div class="sixteen columns">
	<h1><span>The Amsterdam Area wants YOU!</span></h1>
	<p>Many ICT and digital experts believe that the Amsterdam Metropolitan Area is well on the way to becoming Europe’s Silicon Valley, while others praise the outstanding quality of life in the region. One thing’s for sure: with a talented population drawing from a pool of around 180 different nationalities, Amsterdam is a magnet for international talent.</p> 
	<p>Some key facts about the Amsterdam Metropolitan Area:
		<ul class="list">
			<li>It’s home to the most active population of social media users (Twitter, LinkedIn, Yammer) in the world (source: ComScore)</li>
			<li>It has the highest percentage of high-speed broadband adoption in Europe (source: Akamai’s State of the Internet report)</li>
			<li>The Dutch app industry was ranked 4th in the world for app development (source: AppsGeyser)</li>
			<li>The online gaming market is the 3rd biggest in Europe (source: PwC Media Outlook)</li>
			<li>The city is home to ‘The Next Web’, one of the world’s leading blogs about the internet, business and culture (source: Technorati)</li>
			<li>Amsterdam was ranked 3rd in the world regarding development of cross media entertainment formats (source: FremantleMedia)</li>
			<li>The BBC declared Amsterdam one of the leading Smart Cities in the world; plus it was rated as the 3rd Smartest City in Europe according to FastCompany</li>
			<li>Amsterdam was ranked 4th on the Creative Class City index (source: Martin Prosperity Institute)</li>
			<li>There is a vibrant app community comprised of more than 2,000 registered app developers (source: Appsterdam)</li>
			<li>It is the home of Droidcon, the world’s leading Android Developer conference.</li>
		</ul>
	</p>
	<p>Amsterdam inbusiness is the official foreign investment agency of the Amsterdam Metropolitan Area. We aim to help international businesses and professionals establish or expand within the region. Our services are free, confidential and without obligation. Interested in what we can do for you? Don’t hesitate to <a href="/contact" title="Contact us" alt="Contact us">contact</a> us.</p>
	<p><a href="http://www.iamsterdam.com/cloudstack" target="_blank" title="www.iamsterdam.com/cloudstack" alt="www.iamsterdam.com/cloudstack">www.iamsterdam.com/cloudstack</a></p>
	</div>
</div>
