<h1><span>Call for papers</span></h1>
<br>

<div class="eight columns alpha">
<p>The program committee will be looking for presentations and workshops related to working with and developing Apache CloudStack. This includes everything from running CloudStack at scale, best practices for working with IaaS clouds, discussions about CloudStack’s architecture, proposals for feature development, and more. We’re also open to talks that go hand-in-hand with managing Apache CloudStack, like configuration management and monitoring tools.</p>
<p>This event will have a dedicated track aimed at current and aspiring CloudStack developers, the program committee would like to invite members of the community to submit proposals for talks and/or workshops aimed at getting developers familiar with CloudStack and how to extent the possibilities of CloudStack.</p>
<p>The program committee would like to include a dedicated track where companies can showcase products based on or using Apache CloudStack. </p> </div>

<div class="eight columns omega">
<p>The program committee is aiming to provide the opportunity for companies to showcase how their product enriches the Apache CloudStack ecosystem. Please submit a proposal during the call for papers clearly indicating it is for this track.</p>
<p>In short, if it’s relevant to Apache CloudStack development, deployment, and integration, we’re interested in what you might have to say. For an example of what we’re looking for, check out some of the videos from last year’s event.</p>
<p>Please send your paper to <span class="blue">cfp (at) cloudstackcollab.org</span></a>. A complete abstract should at least contain a title, a short bio and a summary of the talk and tell us what kind of format you want, for example a presentation or a workshop. If you have a particular track (developer, user or commercial) in mind for your talk include that as well. If we have any questions regarding your submission we will contact you by email.</p>
</div>
<br>
<h2>Current proposals</h2>
<p>Currently we received already a lot of proposals for the conference. A lot of them are not complete yet on abstracts or bios. Once complete this site will be adjusted accordingly</p>
<div class="sixteen columns alpha">
<table border="1" align="left">
    <tr>
        <th style='width: 170px'><h4>Title</h4></th>
        <th style='width: 140px'><h4>Speaker</h4></th>
        <th><h4>Bio</h4></th>
        <th><h4>Abstract</h4></th>
    </tr>
    <tr>
        <td>The Goat and Silo: What an Old Calculus Problem Can Teach Us about Instilling the Culture Required for Cloud</td>
        <td>Michael Ducy</td>
        <td>Michael Ducy currently works as an Enterprise Architect for Opscode focused on designing and implementing automation solutions for customer’s Cloud, IT Automation, and Continuous Delivery needs. Prior to Opscode, Michael worked at CompuCom, helping with the architecture and design of CompuCom’s Cloud portfolio. Michael has held other roles as a Cloud Architect, Performance and Capacity Planner, Linux Systems Engineer, Instructor of IT courses, and Private Consultant for companies such as enStratus, BMC Software, and Orbitz Worldwide. After graduating from the University of Missouri St. Louis with a degree in Computer Science, Michael completed his Masters degree in Computer Science at the University of Chicago. More recently Michael completed his MBA at the Fisher College of Business at The Ohio State University.</td>
        <td>We may know the Goat and Silo problem as a common calculus mathematical problem, but Goats (scape goats) and Silo (organizational silos) problems also plague IT organizations.  How can we turn Goats and Silos into assets that can help in implementing a culture supportive of Cloud, DevOps, and the next generation of IT paradigms. This talk will build on Organizational Management philosophies, as well as the philosophies of Lean and Agile.<br></td>
    </tr>
    <tr>
        <td>Fault tolerant and scalable CloudStack deployment using Regions</td>
        <td>Kishan Kavala</td>
        <td>Kishan Kavala has 9 years of product development experience in Infrastructure and Virtualization domain. He is an Apache CloudStack committer and is currently working with Citrix Systems. He was also part of the cloud.com team prior to acquisition. He has been working on CloudStack development for the past 3.5 years and was involved in the development of features like Regions, Usage, Snapshots and VPC. He has conducted DevCloud sessions at CloudStack meetups in Hyderabad and also at foss.in event in Bangalore</td>
        <td>"Regions feature was added to CloudStack in 4.1. Regions enable deployment of fault tolerant cloud workloads. Higher availability of the services deployed on CloudStack, lower latency, geographic grouping of cloud resources, complying with geo-specific legal Talk will cover following:
- Regions implementation in CloudStack
- Multi-region CloudStack deployment (CloudStack Admin)
- Designing fault tolerant services on CloudStack using Regions (CloudStack Users)
- Making the most of region-wide services like GSLB, Object Store
requirements are some of the advantages of using Regions. "<br></td>
    </tr>
    <tr>
        <td>CloudStack Networking Deep Dive</td>
        <td>Chiradeep Vittal</td>
        <td>Chiradeep Vittal is a committer and PMC member in the Apache CloudStack project. He has previously presented at OSCON 2012,  LISA 2012 and ApacheCon 2013 on networking in IAAS clouds. He is the primary architect of many of the network function virtualization services available in CloudStack and has been involved in the project since 2008. He is a senior architect in the Cloud Platforms Group in Citrix Systems.</td>
        <td>"Networking in CloudStack is full-featured, full of bells and whistles and by necessity complicated. This session will take cloud operators through the ins-and-outs of CloudStack Networking. Attendees will learn the motivations behind how CloudStack networking is architected, solutions to common networking  requirements, gotchas, troubleshooting CloudStack networking and finally some future directions for theses features.
It is assumed that attendees will have some experience administering CloudStack clouds."<br></td>
    </tr>
    <tr>
        <td>Summary of CloudStack Google Summer of Code Projects</td>
        <td>Sebastien Goasguen </td>
        <td>Sebastien Goasguen is a committer and PMC member of Apache CloudStack.  He has over 10 years of experience in distributed systems and virtualization. He presented at LinuxCon NA 2012, ApacheCon NA 2013, OSCON 2013 on various CloudStack topics. He contributed to Opennebula and has been working on Apache Libcloud. In summer 2013 he coordinated the five Google summer of code projects awarded to Apache CloudStack.</td>
        <td>Google Summer of Code is a well known internship program sponsored by Google. It brings students from all over the world within Open Source Communities to learn the OSS development mechanisms and the OSS mindset. In 2013 CloudStack was awarded five GSoC project: LDAP integration, SDN extension, Improved GUI, Integration with Apache Whirr and integration with Apache Mesos. Of the five project, one failed at mid-term and one led to Apache committer status for one of the students. In this presentation we will explain the GSoC project and how it can benefit CloudStack, we will review the work done in each project and demo the new functionalities it brought to CloudStack<br></td>
    </tr>
    <tr>
        <td>A Google Compute Engine Interface to CloudStack</td>
        <td>Sebastien Goasguen </td>
        <td>Sebastien Goasguen is a committer and PMC member of Apache CloudStack.  He has over 10 years of experience in distributed systems and virtualization. He presented at LinuxCon NA 2012, ApacheCon NA 2013, OSCON 2013 on various CloudStack topics. He contributed to Opennebula and has been working on Apache Libcloud. In summer 2013 he coordinated the five Google summer of code projects awarded to Apache CloudStack.</td>
        <td>Google Summer of Code is a well known internship program sponsored by Google. It brings students from all over the world within Open Source Communities to learn the OSS development mechanisms and the OSS mindset. In 2013 CloudStack was awarded five GSoC project: LDAP integration, SDN extension, Improved GUI, Integration with Apache Whirr and integration with Apache Mesos. Of the five project, one failed at mid-term and one led to Apache committer status for one of the students. In this presentation we will explain the GSoC project and how it can benefit CloudStack, we will review the work done in each project and demo the new functionalities it brought to CloudStack<br></td>
    </tr>
    <tr>
        <td>Apache libcloud and Apache CloudStack</td>
        <td>Sebastien Goasguen </td>
        <td>Sebastien Goasguen is a committer and PMC member of Apache CloudStack.  He has over 10 years of experience in distributed systems and virtualization. He presented at LinuxCon NA 2012, ApacheCon NA 2013, OSCON 2013 on various CloudStack topics. He contributed to Opennebula and has been working on Apache Libcloud. In summer 2013 he coordinated the five Google summer of code projects awarded to Apache CloudStack.</td>
        <td>Google Summer of Code is a well known internship program sponsored by Google. It brings students from all over the world within Open Source Communities to learn the OSS development mechanisms and the OSS mindset. In 2013 CloudStack was awarded five GSoC project: LDAP integration, SDN extension, Improved GUI, Integration with Apache Whirr and integration with Apache Mesos. Of the five project, one failed at mid-term and one led to Apache committer status for one of the students. In this presentation we will explain the GSoC project and how it can benefit CloudStack, we will review the work done in each project and demo the new functionalities it brought to CloudStack<br></td>
    </tr>
    <tr>
        <td>Talk on Apache CloudStack test infrastructure and future goals</td>
        <td>Prasanna Santhanam</td>
        <td>I have been involved in the testing of Apache CloudStack since its initial days at cloud.com. I'm deeply interested in automating infrastructure problems to make the lives of those deploying such large scale systems easier. I maintain and develop the CloudStack community infrastructure along side related projects like the Apache CloudStack - Simulator Hypervisor and Apache CloudStack - Marvin test framework. I'm also a committer and member of the Apache CloudStack PMC.</td>
        <td>"The focus of this talk is on the challenges overcome in setting up repeatable cloud infrastructure using Apache CloudStack for testing Apache CloudStack.
Dogfooding has provided us with a great way to push testing of cloud systems and turn them in to test-as-a-service clouds. The Apache CloudStack test infrastructure brings together such a solution for operators and quality assurance teams to deploy continuous integration systems that are remotely managed, monitored and be used as test beds. The talk will also focus on the future directions of this infrastructure and show how companies deploying cloudstack can readily get involved in quality assurance through the shared use of such test infrastructure."<br></td>
    </tr>
</table>
</div>