<h1><span>Contact</span></h1>
<div class="sixteen columns alpha"> 
	<p>We would like to hear from you. If you have an questions, remarks or other things you want to share with the conference organizers<br/>feel free to contact us at one of the email addresses <span class="blue">info (at) cloudstackcollab.org</span>.</p> 
	<p>For queries regarding sponsoring please use the email address <span class="blue">sponsors (at) cloudstackcollab.org</span>.</p>
	<h2>Invitation letters and visa</h2>
	<p>Some attendees require an invitation letter for their visa. This letter and Short stay Visa for the Netherlands information can be found <a href="\pages\invitationletter.docx" title="Invitation letter" alt="Invitation letter">here.</a></p>
	<p>Please adjust the letter and mail it to <span class="blue">info (at) cloudstackcollab.org</span>. We will send you a signed letter back as soon as possible so you can progress with visas and such.</p>
</div>

