<div class="sixteen columns">
	<h1><span>Contact</span></h1>
	<p>We would like to hear from you. If you have an questions, remarks or other things you want to share with the conference organizers feel free to contact us at one of the email addresses listed below.</p>
	<p>The organisation of the CloudStack Collaboration Conference can be reached at the email address <a href="mailto:info@cloudstackcollab.org" title="info (at) cloudstackcollab.org" alt="info (at) cloudstackcollab.org">info (at) cloudstackcollab.org</a>.</p>
	<p>For queries regarding sponsoring please use the email address <a href="mailto:sponsoring@cloudstackcollab.org" title="sponsoring (at) cloudstackcollab.org" alt="sponsoring (at) cloudstackcollab.org">sponsoring (at) cloudstackcollab.org</a>.</p>
</div>