<div class="sixteen columns">
	<h1><span>Event</span></h1>
	<div class="four column alpha">
		<a class="green-button" href="/event/CloudStack-CIO-event" title="CloudStack CIO event" alt="CloudStack CIO event">CloudStack CIO event</a>
	</div>
	<div class="four column">
		<a class="green-button" href="/event/registration" title="Registration" alt="Registration">Registration</a>
	</div>
	<div class="four column">
		<a class="green-button" href="/event/hotels" title="Hotels" alt="Hotels">Hotels</a>
	</div>
	<div class="four column omega">
		<a class="green-button" href="/event/about-amsterdam" title="About Amsterdam" alt="About Amsterdam">About Amsterdam</a>
	</div>
</div>
