<div class="sixteen columns">
	<h1><span>Event</span></h1>
	<div class="one-third column alpha">
		<a class="green-button" href="/event/CloudStack-CIO-event" title="CloudStack CIO event" alt="CloudStack CIO event">CloudStack CIO event</a>
	</div>
	<div class="one-third column">
		<a class="green-button" href="/event/hotels" title="Hotels" alt="Hotels">Hotels</a>
	</div>
	<div class="one-third column omega">
		<a class="green-button" href="/event/hotels" title="Hotels" alt="Hotels">Hotels</a>
	</div>
</div>