<div class="sixteen columns green-box">
	<h1 class="white"><span>And this is why you should be there!</span></h1>
	<h2>Select one of the livestreams below</h2>
	<div class="four columns alpha">
		<h2 class="white italic"><a href="http://new.livestream.com/ccc2013-1/events/2562727" title="Livestream" alt="Livestream">Effectenbeurs</a></h2>

	</div>
	<div class="four columns">
		<h2 class="white italic"><a href="http://new.livestream.com/ccc2013-2/events/2562871" title="Livestream" alt="Livestream">Veiling zaal</a></h2>
	</div>
		<div class="four columns">
		<h2 class="white italic"><a href="http://new.livestream.com/ccc2013-3/events/2562868" title="Livestream" alt="Livestream">Administratiezaal</a></h2>
	</div>
	<div class="four columns omega">
		<h2 class="white italic"><a href="http://new.livestream.com/ccc2013-4/events/2562874" title="Livestream" alt="Livestream">Berlage zaal</a></h2>
		</div>
		<br class="clear"/>
</div>
<br class="clear">
<div class="sixteen columns">
	<div class="two-thirds column alpha">
		<h1><span>About Apache CloudStack</span></h1>
		<p>Apache CloudStack is open source software designed to deploy and manage large networks of virtual machines, as a highly available, highly scalable Infrastructure as a Service (IaaS) cloud computing platform. CloudStack is used by a number of service providers to offer public cloud services, and by many companies to provide an on-premises (private) cloud offering, or as part of a hybrid cloud solution.</p>
		<h2>CloudStack Collaboration Conference EU in Amsterdam</h2>
		<p>With two very successful events in the United States, we are pleased to bring this event to Amsterdam. Located in the centre of Amsterdam, the Beurs van Berlage will provide a fantastic venue to host the CloudStack Collaboration Conference EU.</p>
		<p>Cloud is gaining momentum big time and CloudStack is one of the leading open source platforms for building and managing clouds. From 20 to 22 November leading European cloud developers and users meet in Amsterdam. Aimed at users, developers and everybody else interested in CloudStack, this will be the place to learn more about CloudStack or join the developers to discuss the past, present and future. Following two very successful collaboration events in the United States, this is the first conference of its kind in Europe. The European CloudStack conference will continue with the best ideas from the previous conferences and feature a varied set of presentations. </p>
		<p>The line-up of speakers for Amsterdam includes Chip Childers, VP Apache Cloudstack project, Paula Gould from GreenCloud, Noa Resare from Spotify, cloud-architect Paul Angus from ShapeBlue, DevOps of the first hour Patrick Debois, John Turner and Noel King from Paddy Power, John Willis from Dell (previous Enstratius), Darren Shepherd, senior principal engineer at Citrix and Hugo Trippears from Schuberg Philis.</p>
		<p>A lot of the talks and events at the conference will provide ample opportunity to meet with the cloudstack community and engage in deep discussions with developers and users. The hack-a-thon day will provide an excellent opportunity to turn ideas into practice together with the committers and the sponsors. </p>
		<p>Apache CloudStack is open source software designed to deploy and manage large networks of virtual machines, as a highly available, highly scalable Infrastructure as a Service (IaaS) cloud computing platform. CloudStack is used by high-end service providers to offer public cloud services, and by many companies to provide an on-premises (private) cloud offering, or as part of a hybrid cloud solution. </p>
		<p>The European CloudStack conference will continue with the best ideas from the previous conferences and feature a varied set of presentations. Aimed at users, developers and everybody else interested in cloudstack, this will be the place to learn more about cloudstack or join the developers to discuss the past, present and future.</p>
		<p>Collaboration is key to keep our community vibrant and growing. A lot of the talks and events at the conference will provide ample opportunity to meet with the cloudstack community and engage in deep discussions with developers and users. The hack day will provide an excellent opportunity to turn ideas into practice together with the committers.</p>
		<br class="clear">
		<a href="/event/registration" title="Register now" alt="Register now" class="green-button">Register now</a>
	</div>
	<div class="one-third column omega">
		<h1><span>Twitter</span></h1>
		<a class="twitter-timeline" href="https://twitter.com/search?q=%23CCCEU13" data-widget-id="382846353992187904" data-link-color="#035b90" height="900px" data-chrome="nofooter noborders transparent">Tweets about "#CCCEU13"</a>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	</div>
</div>
