<div class="sixteen columns green-box">
	<h1 class="white"><span>And this is why you should be there!</span></h1>
	<h2>A personal invitation to CCC Europe</h2>
	<div class="one-third column alpha">
		<iframe width="100%" height="164" src="//www.youtube.com/embed/0ABeb-gOksY?controls=0&showinfo=0&rel=0" frameborder="0" allowfullscreen></iframe>
		<h2 class="white italic float-right">Hugo Trippaers</h2>
	</div>
	<div class="one-third column">
		<iframe width="100%" height="164" src="//www.youtube.com/embed/FndJVdtfZiU?controls=0&showinfo=0&rel=0" frameborder="0" allowfullscreen></iframe>
		<h2 class="white italic float-right">Chip Childers</h2>
	</div>
	<div class="one-third column omega">
		<iframe width="100%" height="164" src="//www.youtube.com/embed/l8s-UhRVdlE?controls=0&showinfo=0&rel=0" frameborder="0" allowfullscreen></iframe>
		<h2 class="white italic float-right">Kelcey Damage</h2>
	</div>
</div>
<br class="clear">
<div class="sixteen columns">
	<div class="two-thirds column alpha">
		<h1><span>About Apache CloudStack</span></h1>
		<p>Apache CloudStack is open source software designed to deploy and manage large networks of virtual machines, as a highly available, highly scalable Infrastructure as a Service (IaaS) cloud computing platform. CloudStack is used by a number of service providers to offer public cloud services, and by many companies to provide an on-premises (private) cloud offering, or as part of a hybrid cloud solution.</p>
		<h2>CloudStack Collaboration Conference in Amsterdam</h2>
		<p>We're very exited to announce the European Apache CloudStack Collaboration Conference. With two very successful events in the United States, we are pleased to bring this event to Amsterdam. Located in the centre of Amsterdam, the Beurs van Berlage will provide a fantastic venue to host this event.</p>
		<p>The European CloudStack conference will continue with the best ideas from the previous conferences and feature a varied set of presentations. Aimed at users, developers and everybody else interested in cloudstack, this will be the place to learn more about cloudstack or join the developers to discuss the past, present and future.</p>
		<p>Collaboration is key to keep our community vibrant and growing. A lot of the talks and events at the conference will provide ample opportunity to meet with the cloudstack community and engage in deep discussions with developers and users. The hack day will provide an excellent opportunity to turn ideas into practice together with the committers.</p>
		<br class="clear">
		<a href="/event/registration" title="Register now" alt="Register now" class="green-button">Register now</a>
	</div>
	<div class="one-third column omega">
		<h1><span>Conference</span></h1>
		<h2 class="gray">20 November 2013</h2>
		<h3 class="green">CloudStack Hack Day</h3>
		<hr/>
		<h2 class="gray">21 November 2013</h2>
		<h3 class="green">Conference<br/>Proper Begins</h3>
		<hr/>
		<h2 class="gray">23 November 2013</h2>
		<h3 class="green">Conference Ends</h3>
		<br class="clear">
		<h1><span>Twitter</span></h1>
		<a class="twitter-timeline" href="https://twitter.com/search?q=%23CCCEU13" data-widget-id="382846353992187904" data-link-color="#035b90" height="425px" data-chrome="nofooter noborders transparent">Tweets about "#CCCEU13"</a>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	</div>
</div>
