<div class="sixteen columns">
	<h1><span>Hotels</span></h1>
	<p>Together with <a href="https://preferredreservations.nl/cloudstack-collaboration-conference-europe" target="_blank" title="Preferred" alt="Preferred">Preferred</a> and Beurs van Berlage, CloudStack Collaborarion Conference selected three hotels for your stay during the Conference.<br/>Bookings are made via <a href="https://preferredreservations.nl/cloudstack-collaboration-conference-europe" target="_blank" title="Preferred" alt="Preferred">Preferred</a></p>
	<p>The selected hotels are:</p>
	<h3 class="green">1. Inntel Hotels Amsterdam Centre****<span class="float-right gray italic">from &euro; 175.00</span></h3>
	<p><img src="/images/inntelhotelamsterdamcentre.jpg" title="Inntel Hotels Amsterdam Centre" alt="Inntel Hotels Amsterdam Centre"></p>
	<h3 class="green">2.	Ibis Amsterdam Centre***<span class="float-right gray italic">from &euro; 113.00</span></h3>
	<p><img src="/images/ibisamsterdamcentre.jpg" title="Inntel Hotels Amsterdam Centre" alt="Inntel Hotels Amsterdam Centre"></p>
	<h3 class="green">3.	Doubletree by Hilton Amsterdam Centraal****<span class="float-right gray italic">from &euro; 190.00</span></h3>
	<p><img src="/images/doubletreebyhiltonamsterdam.jpg" title="Inntel Hotels Amsterdam Centre" alt="Inntel Hotels Amsterdam Centre"></p>
	<a class="green-button" href="https://preferredreservations.nl/cloudstack-collaboration-conference-europe" target="_blank" title="More info and booking" alt="More info and booking">More info and booking</a>
</div>