<div class="sixteen columns"> 
	<h1><span>Press releases</span></h1>
	<table class="schedule">
		<tr>
			<th>Date</th>
			<th>Organisation</th>
			<th>Title</th>
		</tr>
		<tr>
			<td class="time" width="100">21-11-2013</td>
			<td class="room" width="140">Apalia</td>
			<td class="info">
				<span class="title"><h1 class="title"><div class="more-info-click">+</div>3 years partnership anniversary between CloudStack and Apalia</h1></span>
				<div class="more-info">
					<p><strong>Amsterdam, November 20
						2013 – APALIA, an advisory and engineering firm, specialized in
						Private, Hybrid, and Public Cloud infrastructure is proud to announce its 3 years
						partnership anniversary with CloudStack at the Apache CloudStack Collaboration
						Conference Europe.
						</strong></p><br/>
					<p>Pierre Vacherand, founder and CTO of Apalia, hosts  two workshops on November 21 and 22. He will provide 
with practical insights based on 3 years handsIon experience with CloudStack. The  first workshop  focuses on 
the challenges to implementing CloudStack in various production environments, and the second highlights how 
powering  up  CloudStack  with  Amysta™,  a  software  solution  for  Cloud  Computing  cost  control  and  usage 
visibility.</p><br/>
					<p>Apalia, one of the European Cloud Computing pioneers, assists customers all around the world to design, build 
and operate Private, Hybrid and Public Cloud infrastructures in the perspective of “IT as a Service”. Since 2010 
Apalia  helps  Enterprises  and  Service  Providers  to  modernizing  their  IT  infrastructure,  increasing their agility 
thus benefits, and optimizing their expenditures.</p><br/>
					<p>Apalia solution and service offerings cover  the virtualized and secured Cloud infrastructures  (IaaS), as well as 
mobility  (EMM)  and  desktops  (VDI)  including the System,  Networking,  Storage,  Desktop,  Orchestration,  and 
Governance subsets. </p><br/>
					<strong>About APALIA</strong><br/>
					<p>Cloud  computing  brings  innovative  approach  and  technologies  to  modernize  the  Information  Systems’ 
Infrastructure.  Since  its  inception  in  2010,  APALIA  uses  virtualization  and  Cloud  Computing  to  enable 
customers  to  implement  the  "IT  as  a  Service"  model.  The proven  innovative technologies  and  operational 
processes  recommended  by APALIA enable  greater  agility,  enhanced  security,  increased  productivity,  and 
reduced  costs  for  the  benefit  of  the Organizations’ IT departments, and  ultimately  the endIusers experience 
and business efficiency.</p><br/><br/>
					<p>For more information:</p><br/><br/>
					<p>APALIA: www.apalia.net | info@apalia.net | @Apalia</p><br/>
					<p>AMYSTA: www.amysta.com | info@amysta.com | @AmystaBilling</p><br/>
					<p>http://cloudstackcollab.org/ | #CCCEU13</p>
					<p>Contact Apalia Amysta</p><br/><br/>
					<p>Pierre Vacherand I Tel.: EU: +33 6 08 23 95 65 I US: +1I650I238I4429 I pierre.vacherand@apalia.net </p><br/><br/>
					<br/><br/>
					<a class="green-button" target="_blank" href="/downloads/CCC 2013- Apalia.pdf" title="Click to download the press release" alt="Click to download the press release">Click to download this press release</a>
				</div>
			</td>
		</tr>
		<tr>
			<td class="time" width="100">21-11-2013</td>
			<td class="room" width="140">Ikoula</td>
			<td class="info">
				<span class="title"><h1 class="title"><div class="more-info-click">+</div>The Cloud is no longer a concept - it’s a reality</h1></span>
				<div class="more-info">
					<a class="green-button" target="_blank" href="/downloads/CCCEU13- Ikoula.pdf" title="Click to download the press release" alt="Click to download the press release">Click to download this press release</a>
				</div>
			</td>
		</tr>
		<tr>
			<td class="time" width="100">23-10-2013</td>
			<td class="room" width="140">CloudStack Collaboration Conference</td>
			<td class="info">
				<span class="title"><h1 class="title"><div class="more-info-click">+</div>First European Cloudstack Conference,<br/>20-22 november Leading users, developers<br/>and strategists meet in Amsterdam</h1></span>
				<div class="more-info">
					<p><strong>AMSTERDAM, 15 October 2013 - Cloud is gaining momentum big time and CloudStack is one of the leading open source platforms for building and managing clouds. From 20 to 22 November leading European cloud developers and users meet in Amsterdam. Aimed at users, developers and everybody else interested in CloudStack, this will be the place to learn more about CloudStack or join the developers to discuss the past, present and future. Following two very successful collaboration events in the United States, this is the first conference of its kind in Europe. The European CloudStack conference will continue with the best ideas from the previous conferences and feature a varied set of presentations.</strong></p><br/>
					<p>The line-up of speakers for Amsterdam includes Chip Childers, VP Apache Cloudstack project, Paula Gould from GreenCloud, Noa Resare from Spotify, cloud-architect Paul Angus from ShapeBlue, DevOps of the first hour Patrick Debois, John Turner and Noel King from Paddy Power, John Willis from Dell (previous Enstratius), Darren Shepherd, senior principal engineer at Citrix and Hugo Trippears from Schuberg Philis.</p><br/>
					<p>A lot of the talks and events at the conference will provide ample opportunity to meet with the cloudstack community and engage in deep discussions with developers and users. The hack-a-thon day will provide an excellent opportunity to turn ideas into practice together with the committers and the sponsors.</p><br/>
					<p>Apache CloudStack is open source software designed to deploy and manage large networks of virtual machines, as a highly available, highly scalable Infrastructure as a Service (IaaS) cloud computing platform. CloudStack is used by high-end service providers to offer public cloud services, and by many companies to provide an on-premises (private) cloud offering, or as part of a hybrid cloud solution.</p><br/>
					<p>The itinerary of this conference can be found at <a target="_blank" href="http://cloudstackcollab.org/schedule" title="Conference itinerary" alt="Conference itinerary">http://cloudstackcollab.org/schedule</a>.<br/>
					Visitors of the conference can register here: <a target="_blank" href="http://cloudstackcollab.org/event/registration" title="Register" alt="Register">http://cloudstackcollab.org/event/registration</a>.</p><br/><br/>
					<strong>NOTE FOR THE PRESS</strong><br/>
					<p>Journalists are entitled to a free ticket (Use discount code CCC_LOVES_PRESS, when registering your ticket on the registration page) for the entire three-day event, enabling them to join all sessions of the conference. Press briefings will be held on Thursday, between 2.30 and 4.00 pm. During these short briefings various partners and sponsors will make their official announcements.</p><br/><br/>
					<strong>Exclusive facilities</strong><br/>
					<p>Press and analysts have exclusive access to the facilities in the press room: help desk, press releases from our partners and sponsors, office facilities. If needed, interviews can be set up with speakers and/or conference attendants.</p><br/><br/>
					<p><strong>Contact</strong><br/>
					For more information or requests, please contact:</p><br/>
					<p>
					Lotta Croiset - van Uchelen<br/>
					LvanUchelen(at)schubergphilis.com / +31 6 1400 8292
					</p><br/><br/><p>
					Paul Heere <br/>
					Pheere(at)schubergphilis.com / +31 6 5323 3183</p>
					<br/><br/>
					<a class="green-button" target="_blank" href="/downloads/ccc_press release announcement_v1.0.pdf" title="Click to download the press release" alt="Click to download the press release">Click to download this press release</a>
				</div>
			</td>
		</tr>
	</table>
</div>
</div>