<div class="sixteen columns"> 
	<h1><span>Partners and Sponsors</span></h1>
	<p>CloudStack Collaboration Conference is the European conference where developers, users and decision makers meet to share Cloudstack-initiatives and experiences as well as to discuss new possibilities. The organization will be actively promoting this event to European media and analysts  with the help of our network of communications agencies. </p>
	<p>To ensure you maximize your exposure before and at the show we therefore encourage you to get in touch with our PR team. We offer the following support:</p>
	<p><ol>
	<li>Send us your press releases, for distribution through our conference website and social channels </li>
	<li>Showcase your press materials at the press room in Amsterdam </li>		
	<li>Pitch your official announcements at the 20 minute press briefings on Thursday, from 2.30-4.00 pm</li>
	<li>Get in touch with our press team for special requests</li>
	</ol></p>
	<h3>Contact</h3>
	<p>For more information or requests, please contact our press office:<br>
	Schuberg Philis<br>
	Lotta van Uchelen<br>
	+31 614008292<br>
	<span class="blue">lvanuchelen (at) schubergphilis.com</span><br>
	<br>
	or <br>
	<br>
	Lime Tree / Schuberg Philis<br>
	Paul Heere<br>
	+31 653233183<br>
	<span class="blue">paul (at) lime-tree.nl</span><br></p>
</div>
