<div class="sixteen columns">
	<h1><span>Press coverage</span></h1>
	<div class="four columns alpha line-height-columns">
		<h2>Video</h2>
		<a href="http://open.citrix.com/blog/283-videos-from-the-cloudstack-collaboration-conference-north-america-2013.html" target="_blank" title="Citrix" alt="Citrix">Citrix</a>
		<hr/>
		<a href="http://www.youtube.com/watch?v=HAQxvWMkijE" target="_blank" title="Impression of first day at EU CloudStack Collaboration Conference 2013" alt="Impression of first day at EU CloudStack Collaboration Conference 2013">Impression of first day at EU CloudStack Collaboration Conference 2013</a>
		<hr/>
		<a href="http://www.youtube.com/watch?v=PqLvhJWDuIM&sns=tw" target="_blank" title="Closing video of EU CloudStack Collaboration Conference 2013" alt="Closing video of EU CloudStack Collaboration Conference 2013">Closing video of EU CloudStack Collaboration Conference 2013</a>
		<hr/>
		<a href="http://www.youtube.com/watch?v=QQiiOs2kOuc&feature=share&list=UU4qIbQsqYpKVmSzXlCxvr9A&index=6" target="_blank" title="Apalia  - video press release EU CloudStack conference 2013" alt="Apalia  - video press release EU CloudStack conference 2013">Apalia  - video press release EU CloudStack conference 2013</a>
		<hr/>
		<a href="http://www.youtube.com/watch?v=-jysj5jJn6g&feature=youtu.be" target="_blank" title="iKoula - video press release EU CloudStack conference 2013" alt="iKoula - video press release EU CloudStack conference 2013">iKoula - video press release EU CloudStack conference 2013</a>
		<hr/>
		<a href="http://www.youtube.com/watch?v=oFaMAOscT90&feature=youtu.be" target="_blank" title="ShapeBlue - video press release EU CloudStack conference 2013" alt="ShapeBlue - video press release EU CloudStack conference 2013">ShapeBlue - video press release EU CloudStack conference 2013</a>
		<hr/>
		<a href="http://www.youtube.com/watch?v=S58s2zZR_Mo&feature=youtu.be" target="_blank" title="Schuberg Philis - video press release EU CloudStack conference 2013" alt="Schuberg Philis - video press release EU CloudStack conference 2013">Schuberg Philis - video press release EU CloudStack conference 2013</a>
		<hr/>
		<a href="http://www.youtube.com/watch?v=Wlhh5nJXhgk&feature=youtu.be" target="_blank" title="Nexenta - video press release EU CloudStack conference 2013" alt="Nexenta - video press release EU CloudStack conference 2013">Nexenta - video press release EU CloudStack conference 2013</a>
	</div>
	<div class="four columns line-height-columns">
		<h2>Podcasts</h2>
		<a href="http://cloudevangelist.org/2013/11/21/podcast-the-clash-of-the-casts" target="_blank" title="Clash of the Casts" alt="Clash of the Casts">Clash of the Casts</a>
		<hr/>
		<a href="http://cloudevangelist.org/2013/11/22/hybrid-cloud-environments-sds" target="_blank" title="Hybrid cloud environments sds" alt="Hybrid cloud environments sds">Hybrid cloud environments sds</a>
		<hr/>
		<a href="http://cloudevangelist.org/2013/11/20/cloudstack-conference-europe-2013" target="_blank" title="#CCCEU13" alt="#CCCEU13">#CCCEU13</a>
		<hr/>
		<a href="http://cloudevangelist.org/2013/11/22/podcast-funs-kessen-talks-building-clouds-in-eu-zone/" target="_blank" title="Funs Kessen from Schuberg Philis – Building EU clouds" alt="Funs Kessen from Schuberg Philis – Building EU clouds">Funs Kessen from Schuberg Philis – Building EU clouds</a>
		<hr/>
		<a href="http://ec.libsyn.com/p/d/6/3/d631b8558f5ca87b/Cloud_Evangelist_Podcast_Ep71_GreenQloud.mp3?d13a76d516d9dec20c3d276ce028ed5089ab1ce3dae902ea1d01c08234d9cf5a2fd7&c_id=6443981" target="_blank" title="Tryggvi Lárusson, CTO from GreenQloud, interviewed by Red Hat’s Richard Morrell for CloudEvangelist" alt="Tryggvi Lárusson, CTO from GreenQloud, interviewed by Red Hat’s Richard Morrell for CloudEvangelist">Tryggvi Lárusson, CTO from GreenQloud</a>, interviewed by Red Hat’s Richard Morrell for CloudEvangelist
		<hr/>
		<a href="http://cloudevangelist.org/2013/11/21/podcast-antoine-coetsier-exoscale/" target="_blank" title="Antoine Coetsier from Exoscale in Switzerland, interviewed by Red Hat’s Richard Morrell for CloudEvangelist" alt="Antoine Coetsier from Exoscale in Switzerland, interviewed by Red Hat’s Richard Morrell for CloudEvangelist">Antoine Coetsier from Exoscale in Switzerland</a>, interviewed by Red Hat’s Richard Morrell for CloudEvangelist
		<hr/>
		<a href="http://ec.libsyn.com/p/6/0/2/602be426dbad9aef/Cloud_Evangelist_Podcast_Ep72_Arjan_Eriks.mp3?d13a76d516d9dec20c3d276ce028ed5089ab1ce3dae902ea1d01c08234d9cf5bb17d&c_id=6444388" target="_blank" title="Arjan Eriks from Schuberg Philis, interviewed by Red Hat’s Richard Morrell for CloudEvangelist" alt="Arjan Eriks from Schuberg Philis, interviewed by Red Hat’s Richard Morrell for CloudEvangelist">Arjan Eriks from Schuberg Philis</a>, interviewed by Red Hat’s Richard Morrell for CloudEvangelist
	</div>
	<div class="four columns line-height-columns">
		<h2>Publications</h2>
		<a href="http://computerworld.nl/cloud/80247-stack-wars-die-bestaan-helemaal-niet" target="_blank" title="Computerworld - Stack wars? Die bestaan helemaal niet?" alt="Computerworld - Stack wars? Die bestaan helemaal niet?">Computerworld</a> - Stack wars? Die bestaan helemaal niet?
		<hr/>
		<a href="http://www.automatiseringgids.nl/nieuws/2013/47/cloud-is-klaar-in-2-uur-in-plaats-van-3-maanden " target="_blank" title="AutomatiseringsGids" alt="AutomatiseringsGids">AutomatiseringsGids</a>
		<hr/>
		<a href="http://www.marketwired.com/press-release/solidfire-shapeblue-align-to-tackle-storage-challenges-in-cloud-infrastructures-1853925.htm" target="_blank" title="Market Wired – SolidFire and ShapeBlue" alt="Market Wired – SolidFire and ShapeBlue">Market Wired</a> – SolidFire and ShapeBlue
		<hr/>
		<a href="http://www.einnews.com/pr_news/177355034/apache-cloudstack-matures-with-first-commercial-support-offering" target="_blank" title="PR Newswire – Shapeblue announcement" alt="PR Newswire – Shapeblue announcement">PR Newswire</a> – Shapeblue announcement
		<hr/>
		<a href="http://www.businesswire.com/news/topix/20131120005136/en" target="_blank" title="Business Wire – Nexenta announcement" alt="Business Wire – Nexenta announcement">Business Wire</a> – Nexenta announcement
		<hr/>
		<a href="http://smb.chinabyte.com/484/12778484.shtml" target="_blank" title="ChinaByte.com – CloudStack announcement " alt="ChinaByte.com – CloudStack announcement ">ChinaByte.com</a> – CloudStack announcement
		<hr/>
		<a href="http://www.computable.nl/content/agenda/4923506/1589222/cloudstack-collaboration-conference-europe-amsterdam-2022-november.html" target="_blank" title="Computable" alt="Computable">Computable</a>
		<hr/>
		<a href="http://www.linux-magazin.de/NEWS/Apache-Cloudstack-Konferenz-in-Amsterdam" target="_blank" title="Linux magazine 1" alt="Linux magazine 1">Linux magazine 1</a> and <a href="http://www.linux.com/news/enterprise/cloud-computing/748270-learn-about-user-driven-cloud-computing-at-cloudstack-collaboration-conference-eu" target="_blank" title="Linux magazine 2" alt="Linux magazine 2">Linux magazine 2</a>
	</div>
	<div class="four columns omega line-height-columns">
		<h2>Blogs</h2>
		<a href="http://cloudofdata.tumblr.com/post/67654925076/cloudstack-delivers-with-a-chip" target="_blank" title="Cloudstack delivers with a chip" alt="Cloudstack delivers with a chip">Cloudstack delivers with a chip</a>
		<hr/>
		<a href="http://www.tomaz.me/2013/11/24/cloudstack-collaboration-conference-europe-recap.html#.UpMmIxYLNZQ.twitter" target="_blank" title="CloudStack Collaboration Conference Europe 2013 Recap by Tomaz Muraus" alt="CloudStack Collaboration Conference Europe 2013 Recap by Tomaz Muraus">CloudStack Collaboration Conference Europe 2013 Recap by Tomaz Muraus</a>
		<hr/>
		<a href="https://blogs.apache.org/cloudstack/entry/announcing_the_cloudstack_collaboration_conference" target="_blank" title="Apache blog" alt="Apache blog">Apache blog</a>
		<hr/>
		<a href="http://www.visibilityspots.com/cloudcollab-amsterdam.html" target="_blank" title="Visibilityspots" alt="Visibilityspots">Visibilityspots</a>
		<hr/>
		<a href="http://www.openminds.be/nl/evenementen/detail/cloudstack-collaboration-conference-europe" target="_blank" title="OpenMinds" alt="OpenMinds">OpenMinds</a>
		<hr/>
		<a href="http://www.cupfighter.net/index.php/2013/09/running-cloudstack-4-1-1-on-raspberry-pi-2" target="_blank" title="Cupfighter.net" alt="Cupfighter.net">Cupfighter.net</a>
		<hr/>
		<a href="http://www.cloudmagazine.fr/dotclear/index.php?post/2013/11/04/CloudStack-Collaboration-Conference-Europe-%3A-conf%C3%A9rence-europ%C3%A9enne-du-20-au-22-novembre" target="_blank" title="CloudMagazine" alt="CloudMagazine">CloudMagazine</a>
		<hr/>
		<a href="http://opencontrail.org/events/event/apache-cloudstack-collaboration-2013-conference" target="_blank" title="Open Contrail" alt="Open Contrail">Open Contrail</a>
		<hr/>
		<a href="http://www.citrix.com/events/cloudstack-collaboration-conference-europe.html" target="_blank" title="Citrix 1" alt="Citrix 1">Citrix 1</a> and <a href=" http://open.citrix.com/blog/303-cloudstack-collab-eu-2013-a-cloud-conference-for-users.html" target="_blank" title="Citrix 2" alt="Citrix 2">Citrix 2</a>
		<hr/>
		<a href="http://blog.scalr.com/post/62896596984/choosing-the-right-private-cloud-platform-for-your?utm_content=buffer8f365&utm_source=buffer&utm_medium=twitter&utm_campaign=Buffer" target="_blank" title="Scalr" alt="Scalr">Scalr</a>
		<hr/>
		<a href="https://communities.netapp.com/community/netapp-blogs/cloud/blog/2013/11/18/into-the-cloud-and-back-with-netapp" target="_blank" title="Netapp" alt="Netapp">Netapp</a>
		<hr/>
                <a href="http://linkeddataorchestration.com/2013/11/27/cloudstack-collaboration-conference-eu-2013/" target="_blank" title="George Anadiotis" alt="George Anadiotis">George Anadiotis</a>
	</div>
</div>
