<div class="sixteen columns"> 
	<h1><span>Journalist and analyst</span></h1>
	<p>As a journalist or analyst, you are entitled to a free ticket for the entire event. You are our guest and will be able to join all sessions of the conference.<p>
	<h2>Press briefings</h2>
	<p>We invite you to the press briefings on Thursday, 21 November:</p>
	<table>
		<tr>
			<td width="12%">14:30-14:45</td>
			<td>Ikoula, presented by <a href="http://lanyrd.com/profile/jules-henri-gavetti/" target="_blank" title="Jules-Henri Gavetti" alt="Jules-Henri Gavetti">Jules-Henri Gavetti</a></td>
		</tr>
		<tr>
			<td>14:50-15:05</td>
			<td>Apalia</td>
		</tr>
		<tr>
			<td>15:10-15:25</td>
			<td>Citrix</td>
		</tr>
		<tr>
			<td>15:30-15:45 </td>
			<td>Schuberg Philis: Deploying a bank in 2 hours instead of 3 months, presented by <a href="http://lanyrd.com/profile/arjan-eriks/" target="_blank" title="Arjan Eriks" alt="Arjan Eriks">Arjan Eriks</a>, Customer Operations Manager</td>
		</tr>
		<tr>
			<td>15:50-16:05</td>
			<td>Shape Blue: Apache CloudStack matures with first commercial support offering, presented by <a href="http://lanyrd.com/profile/giles-sirett/" target="_blank" title="Giles Sirett" alt="Giles Siretts">Giles Sirett</a>, CEO</td>
		</tr>
		<tr>
			<td>16:10-16:25</td>
			<td>Nexenta to Extend its Industry Leadership in Software-Defined Storage via Strategic Collaboration around CloudStack Solutions, presented by <a href="http://lanyrd.com/profile/tarkanmaner/" target="_blank" title="Tarkan Maner" alt="Tarkan Maner">Tarkan Maner</a>, CEO</td>
		</tr>
	</table>
	<br/>
	<p>During these short briefings will make their official announcements.
	<br/>
	If you can’t make it to Amsterdam, you can find all press releases at <a href="http://cloudstackcollab.org/press-releases" target="_blank" title="Press releases" alt="Press releases">http://cloudstackcollab.org/press-releases</a>
	<br/>
	In addition, video’s of all pressbriefings will be provided afterwards at the CloudStack YouTube channel: <a href="http://www.youtube.com/user/cloudstack" target="_blank" title="CloudStack YouTube channel" alt="CloudStack YouTube channel">http://www.youtube.com/user/cloudstack</a>
	</p>
	<h2>Livestream of all conference sessions</h2>
	<p>If you can’t make it to the conference, you can follow the sessions behind your desk, via Livestreaming on different channels:</p>
	<p>
	Effectenbeurszaal --> <a href="http://new.livestream.com/ccc2013-1" target="_blank" title="Livestream" alt="Livestream">http://new.livestream.com/ccc2013-1</a>
	<br/>
	Veilingzaal --> <a href="http://new.livestream.com/ccc2013-2" target="_blank" title="Livestream" alt="Livestream">http://new.livestream.com/ccc2013-2</a> 
	<br/>
	Administratie --> <a href="http://new.livestream.com/ccc2013-3" target="_blank" title="Livestream" alt="Livestream">http://new.livestream.com/ccc2013-3</a>
	<br/>
	Berlage zaal --> <a href="http://new.livestream.com/ccc2013-4" target="_blank" title="Livestream" alt="Livestream">http://new.livestream.com/ccc2013-4</a>
	</p>
	<p>Please, pick your favorite sessions from the conference schedule.</p>
	<h2>Live interview via webex</h2>
	<p>If you want to interview any of the key speakers/presenters at this event, we can arrange an interview for you via webex. Send us a mail, and we will get in touch with you soonest.</p>
	<h2>Exclusive facilities</h2>
	<p>Press and analysts have exclusive access to the facilities in the press room: help desk, press releases from our partners and sponsors, office facilities. If needed, we can set up interviews with speakers and/or conference attendants for you.</p>
	<h2>Registration</h2>
	<p>To obtain your free ticket, use the promotion code when filling in the registration form. If you contact us at info (at) cloudstackcollab.org we will give you a 100% discount code</p>
	<h2>Contact</h2>
	<p>For more information or requests, please contact our press office:<br>
	Schuberg Philis<br>
	Lotta van Uchelen<br>
	+31 614008292<br>
	<span class="blue">lvanuchelen (at) schubergphilis.com</span><br>
	<br>
	or <br>
	<br>
	Lime Tree / Schuberg Philis<br>
	Paul Heere<br>
	+31 653233183<br>
	<span class="blue">paul (at) lime-tree.nl</span><br></p>
</div>
