<div class="sixteen columns">
	<h1><span>Press coverage</span></h1>
	<div class="eight columns alpha">
		<h2>News</h2>
		<p>
			<a href="https://blogs.apache.org/cloudstack/entry/announcing_the_cloudstack_collaboration_conference" target="_blank" title="Apache blog" alt="Apache blog">Apache blog</a>
			<br/>
			<a href="http://www.computable.nl/artikel/expertverslag/cloud_computing/4922911/2333364/openstack-summit-storage-en-security.html" target="_blank" title="Computable" alt="Computable">Computable</a>
			<br/>
			<a href="http://www.openminds.be/nl/evenementen/detail/cloudstack-collaboration-conference-europe" target="_blank" title="OpenMinds" alt="OpenMinds">OpenMinds</a>
			<br/>
			<a href="http://www.linux-magazin.de/NEWS/Apache-Cloudstack-Konferenz-in-Amsterdam" target="_blank" title="Linux magazine 1" alt="Linux magazine 1">Linux magazine 1</a> and <a href="http://www.linux.com/news/enterprise/cloud-computing/748270-learn-about-user-driven-cloud-computing-at-cloudstack-collaboration-conference-eu" target="_blank" title="Linux magazine 2" alt="Linux magazine 2">Linux magazine 2</a>
			<br/>
			<a href="http://www.cupfighter.net/index.php/2013/09/running-cloudstack-4-1-1-on-raspberry-pi-2" target="_blank" title="Cupfighter.net" alt="Cupfighter.net">Cupfighter.net</a>
			<br/>
			<a href="http://www.cloudmagazine.fr/dotclear/index.php?post/2013/11/04/CloudStack-Collaboration-Conference-Europe-%3A-conf%C3%A9rence-europ%C3%A9enne-du-20-au-22-novembre" target="_blank" title="CloudMagazine" alt="CloudMagazine">CloudMagazine</a>
			<br/>
			<a href="http://opencontrail.org/events/event/apache-cloudstack-collaboration-2013-conference" target="_blank" title="Open Contrail" alt="Open Contrail">Open Contrail</a>
			<br/>
			<a href="http://dhpa.nl/cloudstack-collaboration-conference-europe.html" target="_blank" title="DHPA" alt="DHPA">DHPA</a>
			<br/>
			<a href="http://shapeblue.com/events/cloudstack-collaboration-conference-europe" target="_blank" title="Shapeblue" alt="Shapeblue">Shapeblue</a>
			<br/>
			<a href="http://www.citrix.com/events/cloudstack-collaboration-conference-europe.html" target="_blank" title="Citrix 1" alt="Citrix 1">Citrix 1</a> and <a href=" http://open.citrix.com/blog/303-cloudstack-collab-eu-2013-a-cloud-conference-for-users.html" target="_blank" title="Citrix 2" alt="Citrix 2">Citrix 2</a>
			<br/>
			<a href="http://solidfire.com/about/events/cloudstack-collaboration-conference-amsterdam" target="_blank" title="SolidFire" alt="SolidFire">SolidFire</a>
		</p>
	</div>
	<div class="eight columns omega">
		<h2>Video</h2>
		<p>
			<a href="http://open.citrix.com/blog/283-videos-from-the-cloudstack-collaboration-conference-north-america-2013.html" target="_blank" title="Citrix" alt="Citrix">Citrix</a>
		</p>
	</div>
</div>
