<div class="sixteen columns"> 
	<h1><span>Journalist and analyst</span></h1>
	<p>As a journalist or analyst, you are entitled to a free ticket for the entire event. You are our guest and will be able to join all sessions of the conference. </p>
	<h3>Press briefings</h3>
	<p>We invite you to the press briefings on Thursday, between 2.30 and 4.00 pm. During these short briefings various partners and sponsors will make their official announcements. Afterwards, you will have the opportunity to have one-on-one interviews with the presenters and officials.</p>
	<h3>Exclusive facilities</h3>
	<p>Press and analysts have exclusive access to the facilities in the press room: help desk, press releases from our partners and sponsors, office facilities. If needed, we can set up interviews with speakers and/or conference attendants for you.</p>
	<h3>Registration</h3>
	<p>To obtain your free ticket, use the promotion code when filling in the registration form. If you contact us at <span class="blue">info (at) cloudstackcollab.org</span> we will give you a 100% discount code</p>
	<h3>Contact</h3>
	<p>For more information or requests, please contact our press office:<br>
	Schuberg Philis<br>
	Lotta van Uchelen<br>
	+31 614008292<br>
	<span class="blue">lvanuchelen (at) schubergphilis.com</span><br>
	<br>
	or <br>
	<br>
	Lime Tree / Schuberg Philis<br>
	Paul Heere<br>
	+31 653233183<br>
	<span class="blue">paul (at) lime-tree.nl</span></p>
</div>
