<div class="sixteen columns"> 
	<h1><span>Press releases</span></h1>
	<table class="schedule">
		<tr>
			<th>Date</th>
			<th>Organisation</th>
			<th>Title</th>
		</tr>
		<tr>
			<td class="time" width="100">23-10-2013</td>
			<td class="room" width="140">CloudStack Collaboration Conference</td>
			<td class="info">
				<span class="title"><h1 class="title"><div class="more-info-click">+</div>First European Cloudstack Conference,<br/>20-22 november Leading users, developers<br/>and strategists meet in Amsterdam</h1>
				<br/>
				<p><strong>AMSTERDAM, 15 October 2013 - Cloud is gaining momentum big time and CloudStack is one of the leading open source platforms for building and managing clouds. From 20 to 22 November leading European cloud developers and users meet in Amsterdam. Aimed at users, developers and everybody else interested in CloudStack, this will be the place to learn more about CloudStack or join the developers to discuss the past, present and future. Following two very successful collaboration events in the United States, this is the first conference of its kind in Europe. The European CloudStack conference will continue with the best ideas from the previous conferences and feature a varied set of presentations.</strong></p></span>
				<div class="more-info">
					<p>The line-up of speakers for Amsterdam includes Chip Childers, VP Apache Cloudstack project, Paula Gould from GreenCloud, Noa Resare from Spotify, cloud-architect Paul Angus from ShapeBlue, DevOps of the first hour Patrick Debois, John Turner and Noel King from Paddy Power, John Willis from Dell (previous Enstratius), Darren Shepherd, senior principal engineer at Citrix and Hugo Trippears from Schuberg Philis.</p><br/>
					<p>A lot of the talks and events at the conference will provide ample opportunity to meet with the cloudstack community and engage in deep discussions with developers and users. The hack-a-thon day will provide an excellent opportunity to turn ideas into practice together with the committers and the sponsors.</p><br/>
					<p>Apache CloudStack is open source software designed to deploy and manage large networks of virtual machines, as a highly available, highly scalable Infrastructure as a Service (IaaS) cloud computing platform. CloudStack is used by high-end service providers to offer public cloud services, and by many companies to provide an on-premises (private) cloud offering, or as part of a hybrid cloud solution.</p><br/>
					<p>The itinerary of this conference can be found at <a target="_blank" href="http://cloudstackcollab.org/schedule" title="Conference itinerary" alt="Conference itinerary">http://cloudstackcollab.org/schedule</a>.<br/>
					Visitors of the conference can register here: <a target="_blank" href="http://cloudstackcollab.org/event/registration" title="Register" alt="Register">http://cloudstackcollab.org/event/registration</a>.</p><br/><br/>
					<strong>NOTE FOR THE PRESS</strong><br/>
					<p>Journalists are entitled to a free ticket (Use discount code (mail to info(at)cloudstackcollab.org), when registering your ticket on the registration page) for the entire three-day event, enabling them to join all sessions of the conference. Press briefings will be held on Thursday, between 2.30 and 4.00 pm. During these short briefings various partners and sponsors will make their official announcements.</p><br/><br/>
					<strong>Exclusive facilities</strong><br/>
					<p>Press and analysts have exclusive access to the facilities in the press room: help desk, press releases from our partners and sponsors, office facilities. If needed, interviews can be set up with speakers and/or conference attendants.</p><br/><br/>
					<p><strong>Contact</strong><br/>
					For more information or requests, please contact:</p><br/>
					<p>
					Lotta Croiset - van Uchelen<br/>
					LvanUchelen(at)schubergphilis.com / +31 6 1400 8292
					</p><br/><br/><p>
					Paul Heere <br/>
					Pheere(at)schubergphilis.com / +31 6 5323 3183</p>
					<br/><br/>
					<a class="green-button" target="_blank" href="/downloads/ccc_press_release_announcement.pdf" title="Click to download the press release" alt="Click to download the press release">Click to download this press release</a>
				</div>
			</td>
		</tr>
	</table>
</div>
</div>