<h1><span>General info</span></h1>
<div class="sixteen columns alpha"> 
	<p>Your presence at the "CloudStack Collaboration Conference Europe" could be a very important investment to make in 2013. Cloud is gaining momentum big time and CloudStack is one of the leading open source platform for building clouds. The future of Cloud computing is shaped at events like this. We know it is hard to step away from our busy schedules. But from time to time it is a good thing to step back and look around on what is happening. How is cloud computing being adopted in Europe and Asia? The new ideas, technology developments and implementation show you the exact status of Cloud Computing in 2013 and the near future.</p> 
	<p>CloudStack Collaboration Conference is a good reason to make time for this deep dive. We as organizers have worked very hard to create a conference with very nice content, but also a conference with a lot of opportunity to speak to leading technicians, industry\Õs top vendors and peers from Europe, Asia and the United States.
Come to Amsterdam to meet the frontrunners in cloud computing, test your assumptions and collect stories that will inspire your readers.</p>
	
	<h2>Journalist and analyst section</h2>
	<p>As a journalist or analyst, you are entitled to a free ticket for the entire event. You are our guest and will be able to join all sessions of the conference. </p>
	<h3>Press briefings</h3>
	<p>We invite you to the press briefings on Thursday, between 2.30 and 4.00 pm. During these short briefings various partners and sponsors will make their official announcements. Afterwards, you will have the opportunity to have one-on-one interviews with the presenters and officials.</p>
	<h3>Exclusive facilities</h3>
	<p>Press and analysts have exclusive access to the facilities in the press room: help desk, press releases from our partners and sponsors, office facilities. If needed, we can set up interviews with speakers and/or conference attendants for you.</p>
	<h3>Registration</h3>
	<p>To obtain your free ticket, use the promotion code when filling in the registration form. If you contact us at <span class="blue">info (at) cloudstackcollab.org</span> we will give you a 100% discount code</p>
	<h3>Contact</h3>
	<p>For more information or requests, please contact our press office:<br>
	Schuberg Philis<br>
	Lotta van Uchelen<br>
	+31 20 750 6588<br>
	lvanuchelen@schubergphilis.com<br>
	<br>
	or <br>
	<br>
	Lime Tree / Schuberg Philis<br>
	Paul Heere<br>
	+31 653233183<br>
	paul@lime-tree.nl<br></p>
	<h3>Partners and Sponsors</h3>
	<p>CloudStack Collaboration Conference is the European conference where developers, users and decision makers meet to share Cloudstack-initiatives and experiences as well as to discuss new possibilities. The organization will be actively promoting this event to European media and analysts  with the help of our network of communications agencies. </p>
	<p>To ensure you maximize your exposure before and at the show we therefore encourage you to get in touch with our PR team. We offer the following support:</p>
	<ul>
	<li>Send us your press releases, for distribution through our conference website and social channels </li>
	<li>Showcase your press materials at the press room in Amsterdam </li>		
	<li>Pitch your official announcements at the 20 minute press briefings on Thursday, from 2.30-4.00 pm</li>
	<li>Get in touch with our press team for special requests</li>
	</ul>

</div>

