<div class="sixteen columns"> 
	<h1><span>Press releases</span></h1>
	<table class="schedule">
		<tr>
			<th>Date</th>
			<th>Organisation</th>
			<th>Title</th>
		</tr>
		<tr>
			<td class="time" width="100">21-11-2013</td>
			<td class="room" width="140">Nexenta</td>
			<td class="info">
				<span class="title"><h1 class="title"><div class="more-info-click">+</div>Nexenta to Extend its Industry Leadership in Software-Defined Storage via Strategic Collaboration around CloudStack Solutions</h1></span>
				<div class="more-info">
					<p><strong>Amsterdam, The Netherlands and Santa Clara, CA USA, 20 November 2013—Nexenta (@Nexenta), the global leader in Software-Defined Storage (SDS) (#softwaredefinedstorage), today announced a collaboration with Opscode® Enterprise Chef™ to help CloudStack customers provision and automate their storage, creating the Software-Defined Data Center of the future. The solution will be demonstrated at the CloudStack Collaboration Conference in Beurs van Berlage, Amsterdam, 20-22 November. </strong></p><br/>
					<p> The combination of Opscode Enterprise Chef and Nexenta, which is already installed at leading Netherlands-based IT outsourcer Schuberg Philis (@schubergphilis), helps users configure their entire hybrid cloud application including the compute, network and storage infrastructure all the way through to application delivery. By augmenting CloudStack with Enterprise Chef and Nexenta, customers can guarantee 100 percent functional uptime on their mission critical application infrastructure, bolstered with the right amount of storage. </p><br/>
					<p>The integrated Chef code with NexentaStor allows the entire storage systems for primary or secondary CloudStack storage to be tuned and delivered in a consistent reliable way. This removes the human error from the equation, increasing reliability. Automation of numerous NexentaStor arrays brings Software-Defined Storage to the next step in the Software-Defined Data Center. </p><br/>
					<p>"Chef code can be deployed to tune NexentaStor as needed for each unique group within an organization," states Ken Cheney, Vice President of Business Development for Opscode. "This combination presents a unified storage pool to both the CloudStack deployment and any other systems simultaneously via NFS, automating storage resources at the software layer to minimize management."</p><br/>
					<p>Nexenta will demonstrate the solution at the conference. In addition, Nexenta will present a cloud storage workshop with Schuberg Philis: </p><br/>
					<p>Date: 20th November <br/>Time: 4:00 pm for one hour <br/>Topic: Automating storage for the cloud workshop <br/>Speaker: Mike Letschin and Tarkan Maner, Nexenta and Brenn Oosterbaan, Schuberg Philis</p><br/>
					<p>Dmitry Yusupov, Co-founder of Nexenta, said, "Having 100 percent uptime is business critical for cloud providers. By combining Opscode and NexentaStor, cloud providers can create a unique, highly flexible, hybrid cloud that delivers maximum flexibility and availability and combines the best of storage and networking to create a true Software-Defined Data Center." </p><br/>
					<p>To arrange an interview with Nexenta at Cloudstack contact nexenta@touchdownpr.com. </p>
					<p><strong>About Nexenta</strong><br/>
					<p>Nexenta is the inventor and global leader in Software-Defined Storage. Nexenta delivers secure, high-performance, ultra-scalable, cloud- and virtualization-optimized storage software solutions on any hardware platform realizing the "true" SoftwareDefined Data Center to enable the biggest challenges in IT today; from rich mediadriven Social Media to Big Data; from Internet of Things to Mobility via the Cloud. Built upon an "open platform" and running on a broad choice of industry-standard hardware, Nexenta eliminates vendor lock-in and provides open, secure and scalable unified storage management at significantly lower total cost than legacy systems. Nexenta's global partners include @Cisco, @Dell, @VMware, and other leading IT vendors. </p><br/>
					<p>Contacts: 
					Emily Gallagher / Laura White  <br/>
					Touchdown PR<br/>
					Tel: +44 1252 717040<br/>
					nexenta@touchdownpr.com</p><br/>
					<p>Tim Smith  <br/>
					Element PR <br/>
					Tel: +1-415-350-3019 <br/>
					 pr@nexenta.com</p>
					<br/><br/>
					<a class="green-button" target="_blank" href="/downloads/CCC 2013-Nexenta.pdf" title="Click to download the press release" alt="Click to download the press release">Click to download this press release</a>
				</div>
			</td>
		</tr>
		<tr>
			<td class="time" width="100">21-11-2013</td>
			<td class="room" width="140">ShapeBlue</td>
			<td class="info">
				<span class="title"><h1 class="title"><div class="more-info-click">+</div>Apache CloudStack matures with first commercial support offering</h1></span>
				<div class="more-info">
					<p><strong>CloudStack Collab Conference, Amsterdam – Nov. 20, 2013. ShapeBlue, the leading independent global CloudStack integrator, today announced that it will be the first to offer commercial support of Apache CloudStack. </strong></p><br/>
					<p>ShapeBlue will offer professional, 24x7x365, enterprise grade support for IaaS infrastructures built on Apache CloudStack. The service will offer SLAs and is provided by an organisation that is a centre of excellence in the design and deployment of CloudStack infrastructures. </p><br/>
					<p>Giles Sirett, ShapeBlue CEO, explained: “for 12 months we’ve had increasing demand for formalised CloudStack support services. We support many customers but to date have not offered an SLA-based model. As Apache CloudStack adoption increases we see demand for a service that offers expert support - our customers want the benefits of open source, but also professional, responsive support as with a traditional vendor product.” </p><br/>
					<p>“We can provide this because of the deep knowledge and expertise we have from building some of the world’s largest CloudStack infrastructures, and also our capabilities with associated network, storage and compute technologies. We’ve developed a global support capability in order to offer the high service levels our customers demand. We have piloted the service with a number of customers and received overwhelmingly positive feedback.” </p><br/>
					<p>Regarding ShapeBlue’s involvement with the Apache CloudStack project, Sirett commented:</p><br/>
					<p>“We will be greatly increasing our contribution to the Apache project, with the creation of a dedicated CloudStack Software Engineering Team. Key to us is contributing all of our work back into the project. At this stage, we have no plans to offer a commercial distribution as we feel that this undermines the true value of open source software like CloudStack. Other open source projects suffer from fragmentation by participant vendors and we do not wish this to happen with Apache CloudStack”. </p><br/>
					<p>The core support service will offer heterogeneous support for cloud infrastructures, guaranteed response times of 1 hour for high priority incidents, 24x7x365 coverage and a product patching service. Furthermore, a unique “Instant Guru” service will allow customers to discuss architecture questions and design changes using web-chat, outside of the formalised support structure. </p><br/>
					<p>Sirett concluded: “That demand has been created for this service demonstrates the momentum that Apache CloudStack is gaining. We work hard to make sure that we offer the highest levels of support, delivered by the best people. We are excited to be first in the market with this service.”</p>
					<br/><br/>
					<a class="green-button" target="_blank" href="/downloads/CCC 2013-ShapeBlue.pdf" title="Click to download the press release" alt="Click to download the press release">Click to download this press release</a>
				</div>
			</td>
		</tr>
		<tr>
			<td class="time" width="100">21-11-2013</td>
			<td class="room" width="140">Schuberg Philis</td>
			<td class="info">
				<span class="title"><h1 class="title"><div class="more-info-click">+</div>DEPLOYING A BANK IN 2 HOURS INSTEAD OF 3 MONTHS Schuberg Philis presents dramatic improvements with CloudStack</h1></span>
				<div class="more-info">
					<p><strong>Schiphol-Rijk, 21 November 2013 – Schuberg Philis (@SchubergPhilis) presented at the first European CloudStack Collaboration Conference, their experiences of working with CloudStack. The outsourcing company has developed a CloudStack-based cloud platform for their mission critical application landscapes. The new setup enables Schuberg Philis to deploy complex infrastructures like new internet banks within hours, rather than months. Arjan Eriks, Customer Operations Manager at Schuberg Philis “Availability is becoming a commodity. For the majority of our customers, reducing time-to-market is the key strategic priority. With our combined offering of exceptional engineering skills, devops tooling and the CloudStack platform, we can meet the most extreme customer demands.”</strong></p><br/>
					<p><strong>Configuring the new cloud platform</strong></br>
					At the beginning of 2012, Schuberg Philis decided to build its own cloud infrastructure to meet a number of challenges from customers: improving time-to-market and elasticity in capacity and infrastructure, enabling continuous integration and deployment. In line with these demands, Schuberg Philis sought higher levels of infrastructure automation. This frees up engineering capacity that is needed to dig deeper into customer needs and translate it into added value. Schuberg Philis defined a number of requirements for its cloud platform which included: design for failure, open source where possible, avoid vendor lock-in, design with security in mind, be reusable and automated wherever possible and simple to deploy.</p><br/>
					<p>Schuberg Philis has combined a number of technologies to match these requirements: Cloudstack software, the Chef automation platform, the VMware NSX network virtualisation platform, the NexentaStor storage solution and switches from Arista Networks. Arjan Eriks “With this toolbox we have been able to build a cost effective mission critical cloud platform, that is easily scalable and provides the type of 100% resilience that Schuberg Philis is known for. Our cloud-engineers favour CloudStack for its simplicity and transparency, allowing them to develop and deploy configurations easier than they had ever imagined.”</p><br/>
					<p><strong>Intensive relationships</strong><br/> 
					Arjan Eriks continues “We strongly believe in the power of open source and DevOps. Our team actively participates in the vibrant CloudStack developers-community. The passion and results of this global crew, has allowed this technology to flourish beyond expectations. To comprehend the full potential of CloudStack, you have to be willing to experiment, share and grow fast. Our focus on intensive relationships with customers and technical partners has always been an important fundament for our success. This become even more important when you’re operating ‘from a distance’ in the cloud.”</p><br/>
					<p><strong>About Schuberg Philis </strong><br/>
					Schuberg Philis is a private company and an important player in the field of mission critical outsourcing services. Schuberg Philis exclusively addresses company application infrastructures which require 24/7 availability. It guarantees its customers 100% functional uptime for the applications running on these infrastructures. In 2012, the 165 colleagues realised revenues of € 56.3 million. Schuberg Philis is sharing more and more of its solutions and knowledge in the open source community, as its engineers want to contribute to society. The company will share even more of its expertise in the years to come. Customers are among others Air France-KLM, Loodswezen, bol.com, Rabobank International Direct Banking, ING, ASR Nederland, MoneYou, LeasePlan Bank, Eneco Energy Trade, Syntrus Achmea, Robeco and Vattenfall</p><br/>
					<p><strong>For more information about this news release, please contact Schuberg Philis:</strong></p><br/>
					<p>Paul Heere: +31 (0)6 532 33 183, pheere@schubergphilis.com</p>
					<p>Lotta Croiset van Uchelen: +31 (0)6 140 08 292, lvanuchelen@schubergphilis.com </p>
					<br/><br/>
					<a class="green-button" target="_blank" href="/downloads/CCC 2013-Schuberg Philis.pdf" title="Click to download the press release" alt="Click to download the press release">Click to download this press release</a>
				</div>
			</td>
		</tr>
		<tr>
			<td class="time" width="100">21-11-2013</td>
			<td class="room" width="140">Apalia</td>
			<td class="info">
				<span class="title"><h1 class="title"><div class="more-info-click">+</div>3 years partnership anniversary between CloudStack and Apalia</h1></span>
				<div class="more-info">
					<p><strong>Amsterdam, November 20 2013 – APALIA, an advisory and engineering firm, specialized in Private, Hybrid, and Public Cloud infrastructure is proud to announce its 3 years partnership anniversary with CloudStack at the Apache CloudStack Collaboration Conference Europe.
					</strong></p><br/>
					<p>Pierre Vacherand, founder and CTO of Apalia, hosts two workshops on November 21 and 22. He will provide with practical insights based on 3 years handsIon experience with CloudStack. The first workshop focuses on the challenges to implementing CloudStack in various production environments, and the second highlights how powering up CloudStack with Amysta™, a software solution for Cloud Computing cost control and usage visibility.</p><br/>
					<p>Apalia, one of the European Cloud Computing pioneers, assists customers all around the world to design, build and operate Private, Hybrid and Public Cloud infrastructures in the perspective of “IT as a Service”. Since 2010 Apalia helps Enterprises and Service Providers to modernizing their IT infrastructure, increasing their agility thus benefits, and optimizing their expenditures.</p><br/>
					<p>Apalia solution and service offerings cover the virtualized and secured Cloud infrastructures (IaaS), as well as mobility (EMM) and desktops (VDI) including the System, Networking, Storage, Desktop, Orchestration, and Governance subsets. </p><br/>
					<strong>About APALIA</strong><br/>
					<p>Cloud computing brings innovative approach and technologies to modernize the Information Systems’ Infrastructure. Since its inception in 2010, APALIA uses virtualization and Cloud Computing to enable customers to implement the "IT as a Service" model. The proven innovative technologies and operational processes recommended by APALIA enable greater agility, enhanced security, increased productivity, and reduced costs for the benefit of the Organizations’ IT departments, and ultimately the endIusers experience and business efficiency.</p><br/>
					<p><strong>For more information:</strong></p>
					<p>APALIA: www.apalia.net | info@apalia.net | @Apalia</p>
					<p>AMYSTA: www.amysta.com | info@amysta.com | @AmystaBilling</p><br/>
					<p>http://cloudstackcollab.org/ | #CCCEU13</p><br/>
					<p><strong>Contact Apalia Amysta</strong></p>
					<p>Pierre Vacherand I Tel.: EU: +33 6 08 23 95 65 I US: +1I650I238I4429 I pierre.vacherand@apalia.net </p><br/><br/>
					<a class="green-button" target="_blank" href="/downloads/CCC 2013- Apalia.pdf" title="Click to download the press release" alt="Click to download the press release">Click to download this press release</a>
				</div>
			</td>
		</tr>
		<tr>
			<td class="time" width="100">21-11-2013</td>
			<td class="room" width="140">Ikoula</td>
			<td class="info">
				<span class="title"><h1 class="title"><div class="more-info-click">+</div>The Cloud is no longer a concept - it’s a reality</h1></span>
				<div class="more-info">
					<a class="green-button" target="_blank" href="/downloads/CCCEU13- Ikoula.pdf" title="Click to download the press release" alt="Click to download the press release">Click to download this press release</a>
				</div>
			</td>
		</tr>
		<tr>
			<td class="time" width="100">23-10-2013</td>
			<td class="room" width="140">CloudStack Collaboration Conference</td>
			<td class="info">
				<span class="title"><h1 class="title"><div class="more-info-click">+</div>First European Cloudstack Conference,<br/>20-22 november Leading users, developers<br/>and strategists meet in Amsterdam</h1></span>
				<div class="more-info">
					<p><strong>AMSTERDAM, 15 October 2013 - Cloud is gaining momentum big time and CloudStack is one of the leading open source platforms for building and managing clouds. From 20 to 22 November leading European cloud developers and users meet in Amsterdam. Aimed at users, developers and everybody else interested in CloudStack, this will be the place to learn more about CloudStack or join the developers to discuss the past, present and future. Following two very successful collaboration events in the United States, this is the first conference of its kind in Europe. The European CloudStack conference will continue with the best ideas from the previous conferences and feature a varied set of presentations.</strong></p><br/>
					<p>The line-up of speakers for Amsterdam includes Chip Childers, VP Apache Cloudstack project, Paula Gould from GreenCloud, Noa Resare from Spotify, cloud-architect Paul Angus from ShapeBlue, DevOps of the first hour Patrick Debois, John Turner and Noel King from Paddy Power, John Willis from Dell (previous Enstratius), Darren Shepherd, senior principal engineer at Citrix and Hugo Trippears from Schuberg Philis.</p><br/>
					<p>A lot of the talks and events at the conference will provide ample opportunity to meet with the cloudstack community and engage in deep discussions with developers and users. The hack-a-thon day will provide an excellent opportunity to turn ideas into practice together with the committers and the sponsors.</p><br/>
					<p>Apache CloudStack is open source software designed to deploy and manage large networks of virtual machines, as a highly available, highly scalable Infrastructure as a Service (IaaS) cloud computing platform. CloudStack is used by high-end service providers to offer public cloud services, and by many companies to provide an on-premises (private) cloud offering, or as part of a hybrid cloud solution.</p><br/>
					<p>The itinerary of this conference can be found at <a target="_blank" href="http://cloudstackcollab.org/schedule" title="Conference itinerary" alt="Conference itinerary">http://cloudstackcollab.org/schedule</a>.<br/>
					Visitors of the conference can register here: <a target="_blank" href="http://cloudstackcollab.org/event/registration" title="Register" alt="Register">http://cloudstackcollab.org/event/registration</a>.</p><br/><br/>
					<strong>NOTE FOR THE PRESS</strong><br/>
					<p>Journalists are entitled to a free ticket (Use discount code CCC_LOVES_PRESS, when registering your ticket on the registration page) for the entire three-day event, enabling them to join all sessions of the conference. Press briefings will be held on Thursday, between 2.30 and 4.00 pm. During these short briefings various partners and sponsors will make their official announcements.</p><br/><br/>
					<strong>Exclusive facilities</strong><br/>
					<p>Press and analysts have exclusive access to the facilities in the press room: help desk, press releases from our partners and sponsors, office facilities. If needed, interviews can be set up with speakers and/or conference attendants.</p><br/><br/>
					<p><strong>Contact</strong><br/>
					For more information or requests, please contact:</p><br/>
					<p>
					Lotta Croiset - van Uchelen<br/>
					LvanUchelen(at)schubergphilis.com / +31 6 1400 8292
					</p><br/><br/><p>
					Paul Heere <br/>
					Pheere(at)schubergphilis.com / +31 6 5323 3183</p>
					<br/><br/>
					<a class="green-button" target="_blank" href="/downloads/ccc_press release announcement_v1.0.pdf" title="Click to download the press release" alt="Click to download the press release">Click to download this press release</a>
				</div>
			</td>
		</tr>
	</table>
</div>
</div>