<div class="sixteen columns green-box">
	<h1 class="white"><span>Why sponsor, from our sponsors</span></h1>
	<div class="one-third column alpha">
		<iframe width="100%" height="164" src="//www.youtube.com/embed/VVvD8E4i20M?controls=0&showinfo=0&rel=0" frameborder="0" allowfullscreen></iframe>
		<h2 class="white italic float-right">Giles Sirett</h2>
	</div>
	<div class="one-third column">
		<iframe width="100%" height="164" src="//www.youtube.com/embed/c7s_jHvztnc?controls=0&showinfo=0&rel=0" frameborder="0" allowfullscreen></iframe>
		<h2 class="white italic float-right">Dave Cahill</h2>
	</div>
	<div class="one-third column omega">
		<iframe width="100%" height="164" src="//www.youtube.com/embed/ivGsLcWX-1E?controls=0&showinfo=0&rel=0" frameborder="0" allowfullscreen></iframe>
		<h2 class="white italic float-right">Krishna Subramanian</h2>
	</div>
</div>
<div class="sixteen columns">
	<h1><span>Sponsoring European CloudStack Collaboration Conference</span></h1>
	<div class="eight columns alpha">
		<p>The European CloudStack Collaboration Conference will be a valuable opportunity for members of the CloudStack community to get together, share information, and prepare for the next release cycle of Apache CloudStack.</p>
		<p>The conference wouldn't be possible without the support of companies and organizations interested in promoting and improving CloudStack. We'd like to thank all of the sponsors who've donated or made commitments already, and invite all other interested parties to help support the conference.</p>
		<p>Sponsorship starts at &euro;1,000 to allow even smaller companies to gain exposure in front of the most sophisticated CloudStack audience there is - the developer community!</p>
	</div>
	<div class="eight columns omega">
		<p>The higher levels of sponsorship are naturally given more prominence in the web site and on the on-site conference signage.</p>
		<p>We'll happily work with you to find a sponsorship that fits your needs. The conference is organized by the CloudStack community with support from Schuberg Philis, ShapeBlue, Citrix and other companies. We are grateful to all sponsors for their support, without which the conference wouldn’t be possible, and we like to thank each organization for their support for CloudStack and the conference.</p>
	</div>
</div>